steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-southeast2-docker.pkg.dev/${PROJECT_ID}/hello-app-repo:$SHORT_SHA', 
           '.']
           
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']
options:
  logging: CLOUD_LOGGING_ONLY