steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-southeast2-docker.pkg.dev/playground-sugi/hello-app-repo:$SHORT_SHA', 
           '.']
options:
  logging: CLOUD_LOGGING_ONLY